version: "3.7"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-profile
    ports:
      - "9100:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx

    depends_on:
      - profile-server-1
      - profile-server-2
      - profile-server-3
    networks:
      - profile-network





  # auth-server 인스턴스들을 개별 서비스로 정의 (Compose는 deploy.replicas를 적용하지 않으므로 이렇게 복수 서비스로 표현)
  profile-server-1:
    image: ddingsh9/profile-server:1.7
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    container_name: profile-server-1
    networks:
      - profile-network
      - infra-network


    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 15s
      timeout: 5s
      retries: 3

  profile-server-2:
    image: ddingsh9/profile-server:1.7
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    container_name: profile-server-2
    networks:
      - profile-network
      - infra-network


    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 15s
      timeout: 5s
      retries: 3

  profile-server-3:
    image: ddingsh9/profile-server:1.7
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    container_name: profile-server-3
    networks:
      - profile-network
      - infra-network

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 15s
      timeout: 5s
      retries: 3


networks:
  profile-network:
    driver: bridge
    name: profile-network
  infra-network:
      external: true
      name: infra-network

