version: "3.7"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-profile
    ports:
      - "9100:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx

    depends_on:
      - profile-server-1
      - profile-server-2
      - profile-server-3
    networks:
      - profile-network

  mariadb:
    container_name: mariadbProfile
    image: mariadb:latest
    env_file:
      - .env.prod
    ports:
      - "4000:3306"
    networks:
      - profile-network
    volumes:
      - db-data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5



  # auth-server 인스턴스들을 개별 서비스로 정의 (Compose는 deploy.replicas를 적용하지 않으므로 이렇게 복수 서비스로 표현)
  profile-server-1:
    image: ddingsh9/profile-server:1.3
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    container_name: profile-server-1
    networks:
      - profile-network
    depends_on:
      - mariadb

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 15s
      timeout: 5s
      retries: 3

  profile-server-2:
    image: ddingsh9/profile-server:1.3
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    container_name: profile-server-2
    networks:
      - profile-network
    depends_on:
      - mariadb

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 15s
      timeout: 5s
      retries: 3

  profile-server-3:
    image: ddingsh9/profile-server:1.3
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    container_name: profile-server-3
    networks:
      - profile-network
    depends_on:
      - mariadb

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
  redis:
    image: redis:7-alpine
    container_name: redis-profile
    ports:
      - "6379:6379"   # 호스트에서 접근할 필요 없으면 제거 가능
    networks:
      - profile-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  profile-network:
    driver: bridge
    name: profile-network

volumes:
  db-data:
    driver: local
    name: db-data
